
try {
    let result = 10 / 0;
    // let x = y;
} catch(error) {
    console.log("An error occured " + error.message);
}